lib/mipha_web/router.ex
defmodule MiphaWeb.Router do
  use MiphaWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug Ueberauth
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MiphaWeb.Plug.CurrentUser
    plug MiphaWeb.Plug.Locale
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admin do
    plug :put_layout, {MiphaWeb.LayoutView, :admin}
    plug MiphaWeb.Plug.RequireAdmin
  end

  scope "/auth", MiphaWeb do
    pipe_through(:browser)

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
  end

  scope "/", MiphaWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get "/", TopicController, :index
    get "/search", SearchController, :index
    get "/search/users", SearchController, :users
    get "/markdown", PageController, :markdown
    get("/join", SessionController, :new, as: :join)
    post("/join", SessionController, :create, as: :join)
    get "/excaptcha", SessionController, :excaptcha
    get "/login", AuthController, :login
    get("/logout", AuthController, :delete, as: :logout)

    get "/u/:name", UserController, :show
    get("/u/:name/topics", UserController, :topics, as: :user_topics)
    get("/u/:name/replies", UserController, :replies, as: :user_replies)
    get("/u/:name/stars", UserController, :stars, as: :user_stars)
    get("/u/:name/collections", UserController, :collections, as: :user_collections)
    post("/u/:name/follow", UserController, :follow, as: :user_follow)
    post("/u/:name/unfollow", UserController, :unfollow, as: :user_unfollow)
    get("/u/:name/followers", UserController, :followers, as: :user_followers)
    get("/u/:name/following", UserController, :following, as: :user_following)
    get("/u/:name/reward", UserController, :reward, as: :user_reward)

    get "/users", UserController, :index
    get "/forgot_password", UserController, :forgot_password
    get "/reset_password", UserController, :reset_password
    # get "/verify", UserController, :verify_email
    put "/users/update_password", UserController, :update_password
    post "/users/sent_forgot_password_email", UserController, :sent_forgot_password_email
    post "/users/sent_verify_email", UserController, :sent_verify_email
    resources("/teams", TeamController)
    get "/teams/:id/people", TeamController, :people

    # topic
    get "/jobs", TopicController, :jobs
    get "/topics/no_reply", TopicController, :no_reply
    get "/topics/popular", TopicController, :popular
    get "/topics/featured", TopicController, :featured
    get "/topics/educational", TopicController, :educational

    post "/topics/:id/star", TopicController, :star
    post "/topics/:id/unstar", TopicController, :unstar
    post "/topics/:id/collection", TopicController, :collection
    post "/topics/:id/uncollection", TopicController, :uncollection
    post "/topics/:id/suggest", TopicController, :suggest
    post "/topics/:id/unsuggest", TopicController, :unsuggest
    post "/topics/:id/close", TopicController, :close
    post "/topics/:id/open", TopicController, :open
    post "/topics/:id/excellent", TopicController, :excellent
    post "/topics/:id/normal", TopicController, :normal

    resources "/topics", TopicController do
      resources "/replies", ReplyController do
        post "/star", ReplyController, :star
        post "/unstar", ReplyController, :unstar
      end
    end

    resources("/notifications", NotificationController, only: ~w(index)a)
    post "/notifications/make_read", NotificationController, :make_read
    delete "/notifications/clean", NotificationController, :clean

    resources("/locations", LocationController, only: ~w(index show)a)
    resources("/companies", CompanyController, only: ~w(index show)a)

    # User profile
    resources "/setting", SettingController, only: ~w(show update)a, singleton: true do
      get("/account", SettingController, :account, as: :account)
      get("/password", SettingController, :password, as: :password)
      get("/profile", SettingController, :profile, as: :profile)
      get("/reward", SettingController, :reward, as: :reward)
    end
  end

  scope "/admin", MiphaWeb.Admin, as: :admin do
    pipe_through(~w(browser admin)a)

    get "/", PageController, :index
    resources("/users", UserController, only: ~w(index delete)a)
    resources("/nodes", NodeController)
    resources("/topics", TopicController, only: ~w(index)a)
    resources("/replies", ReplyController, only: ~w(index show delete)a)
    resources("/companies", CompanyController, only: ~w(index delete)a)
    resources("/teams", TeamController, only: ~w(index delete)a)
    resources("/notifications", NotificationController, only: ~w(index show delete)a)
  end

  # Other scopes may use custom stacks.
  scope "/api", MiphaWeb do
    pipe_through(:api)

    post "/topics/preview", TopicController, :preview
    post "/callback/qiniu", CallbackController, :qiniu
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
end

lib/mipha_web/controllers/setting_controller.ex
defmodule MiphaWeb.SettingController do
  use MiphaWeb, :controller

  alias Mipha.{Accounts, Qiniu}

  plug MiphaWeb.Plug.RequireUser

  @intercepted_action ~w(show account password profile reward)a

  def action(conn, _) do
    if Enum.member?(@intercepted_action, action_name(conn)) do
      changeset = Accounts.change_user(current_user(conn))
      render(conn, action_name(conn), changeset: changeset)
    else
      apply(__MODULE__, action_name(conn), [conn, conn.params])
    end
  end

  def update(conn, %{"user" => user_params}) do
    case user_params["by"] do
      "show" -> update_account(conn, user_params)
      "profile" -> update_profile(conn, user_params)
      "password" -> update_password(conn, user_params)
      "reward" -> update_reward(conn, user_params)
    end
  end

  defp update_account(conn, user_params) do
    # FIXME need more better method.
    attrs =
      user_params
      |> Map.pop("avatar")
      |> build_attrs("avatar")

    case Accounts.update_user(current_user(conn), attrs) do
      {:ok, user} ->
        conn
        |> put_flash(:info, gettext("Profile updated successfully"))
        |> render(:show, changeset: Accounts.change_user(user))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:danger, gettext("Profile updated failed"))
        |> render(:show, changeset: changeset)
    end
  end

  defp update_profile(conn, user_params) do
    case Accounts.update_user(current_user(conn), user_params) do
      {:ok, _} ->
        conn
        |> put_flash(:info, gettext("User updated successfully."))
        |> redirect(to: setting_profile_path(conn, :profile))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:danger, gettext("User updated failed."))
        |> render(:password, changeset: changeset)
    end
  end

  defp update_password(conn, user_params) do
    case Accounts.update_user_password(current_user(conn), user_params) do
      {:ok, _} ->
        conn
        |> configure_session(drop: true)
        |> put_flash(:info, gettext("User updated password successfully."))
        |> redirect(to: "/")

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:danger, gettext("Invalid password"))
        |> render(:password, changeset: changeset)

      {:error, reason} ->
        changeset = Accounts.user_update_password_changeset()

        conn
        |> put_flash(:danger, reason)
        |> render(:password, changeset: changeset)
    end
  end

  defp update_reward(conn, user_params) do
    attrs =
      user_params
      |> Map.pop("wechat")
      |> build_attrs("wechat")
      |> Map.pop("alipay")
      |> build_attrs("alipay")

    case Accounts.update_user(current_user(conn), attrs) do
      {:ok, user} ->
        changeset = Accounts.change_user(user)

        conn
        |> put_flash(:info, gettext("User updated successfully."))
        |> render(:show, changeset: changeset)

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:danger, gettext("User updated failed."))
        |> render(:show, changeset: changeset)
    end
  end

  defp build_attrs({nil, params}, _), do: params

  defp build_attrs({%Plug.Upload{} = avatar, params}, field) do
    # FIXME need set global callback
    with %HTTPoison.Response{status_code: 200, body: body} <- Qiniu.upload(avatar.path) do
      Map.merge(params, %{field => body["key"]})
    end
  end
end

lib/mipha_web/setting_controller.ex
defmodule MiphaWeb.SettingController do
  use MiphaWeb, :controller
  alias Mipha.Accounts
  alias Mipha.Accounts.User
  alias Mipha.Qiniu

  plug MiphaWeb.Plug.RequireUser

  @intercepted_action ~w(show account password profile reward)a

  def action(conn, _) do
    if Enum.member?(@intercepted_action, action_name(conn)) do
      changeset = Accounts.change_user(current_user(conn))
      render conn, action_name(conn), changeset: changeset
    else
      apply(__MODULE__, action_name(conn), [conn, conn.params])
    end
  end

  def update(conn, %{"user" => user_params}) do
    case user_params["by"] do
      "show"     ->   update_account(conn, user_params)
      "profile"  ->   update_profile(conn, user_params)
      "password" ->   update_password(conn, user_params)
      "reward"   ->   update_reward(conn, user_params)
    end
  end

  defp update_account(conn, user_params) do
    attrs = %{
      "bio" => user_params["bio"],
      "email_public" => user_params["email_public"]
    }

    if user_params["avatar"] do
      avatar_path = user_params["avatar"].path
      {:ok, key} = upload(conn, avatar_path)
      attrs = Map.merge(attrs, %{"avatar" => key})
    end

    case Accounts.update_user(current_user(conn), attrs) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> render(:show, changeset: Accounts.change_user(user))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:error, "User updated failed.")
        |> render(:show, changeset: changeset)
    end
  end

  defp update_profile(conn, user_params) do
    case Accounts.update_user(current_user(conn), user_params) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: setting_profile_path(conn, :profile))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:error, "User updated failed.")
        |> render(:password, changeset: changeset)
    end
  end

  defp update_password(conn, user_params) do
    case Accounts.update_user_password(current_user(conn), user_params) do
      {:ok, _} ->
        conn
        |> configure_session(drop: true)
        |> put_flash(:info, "User updated password successfully.")
        |> redirect(to: "/")

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:info, "Invalid password")
        |> render(:password, changeset: changeset)

      {:error, reason} ->
        changeset = User.update_password_changeset(%User{}, %{})
        conn
        |> put_flash(:info, reason)
        |> render(:password, changeset: changeset)
    end
  end

  defp update_reward(conn, user_params) do
    attrs = %{}

    if user_params["wechat"] do
      wechat_path = user_params["wechat"].path
      {:ok, key} = upload(conn, wechat_path)
      attrs = Map.merge(attrs, %{"wechat" => key})
    end

    if user_params["alipay"] do
      alipay_path = user_params["alipay"].path
      {:ok, key} = upload(conn, alipay_path)
      attrs = Map.merge(attrs, %{"alipay" => key})
    end

    case Accounts.update_user(current_user(conn), attrs) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> render(:show, changeset: Accounts.change_user(user))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:error, "User updated failed.")
        |> render(:show, changeset: changeset)
    end
  end

  defp upload(conn, path) do
    case Qiniu.upload(path) do
      %HTTPoison.Response{status_code: 200, body: body} ->
        {:ok, body["key"]}

      %HTTPoison.Response{status_code: _} ->
        conn
        |> put_flash(:info, "上传失败")
        |> render(:show, changeset: Accounts.change_user(current_user(conn)))
    end
  end
end

lib/mipha_web/views/setting_view.ex
defmodule MiphaWeb.SettingView do
  use MiphaWeb, :view

  alias Mipha.Accounts

  @doc """
  location select option
  """
  def location_option do
    Accounts.list_locations()
    |> Enum.map(&{&1.name, &1.id})
  end
end

lib/mipha_web/templates/setting/_sidebar.html.eex
<div class="card">
  <ul class="nav nav-pills flex-column nav-stacked mi-nav">
    <li class="nav-item">
      <%= link to: setting_path(@conn, :show), class: "nav-link" do %>
        <i class='fa fa-user-circle'></i>
        <span><%= gettext "Profile" %></span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link to: setting_profile_path(@conn, :profile), class: "nav-link hide-ios" do %>
        <i class='fa fa-address-card'></i>
        <span><%= gettext "Details" %></span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link to: setting_password_path(@conn, :password), class: "nav-link hide-ios" do %>
        <i class='fa fa-keyboard-o'></i>
        <span><%= gettext "Change Password" %></span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link to: setting_reward_path(@conn, :reward), class: "nav-link hide-ios" do %>
        <i class='fa fa-qrcode'></i>
        <span><%= gettext "Reward" %></span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link to: setting_account_path(@conn, :account), class: "nav-link hide-ios" do %>
        <i class='fa fa-gear'></i>
        <span><%= gettext "Setting" %></span>
      <% end %>
    </li>
  </ul>
</div>

lib/mipha_web/templates/setting/account.html.eex
<div class="row">
  <div class="col-sm-2 col-md-offset-1 setting-menu">
    <%= render "_sidebar.html", assigns %>
  </div>

  <div class="col-md-10">
    <div class="card">
      <div class="card-body">
        <div class="heading">删除我的账号(暂不提供该功能)</div>

        <form action="/setting" accept-charset="UTF-8" data-remote="true" method="post">
          <input name="utf8" type="hidden" value="&#x2713;" />
          <input type="hidden" name="_method" value="delete" />
          <input type="hidden" name="authenticity_token" value="FiuBKuNbeu5y1/Mrh8+7MhR7TjIa4/H6C9iIBKHB4C2+v0Jx0xLiOOoCi1ZakrMvgE8HavcalXlJwOJLNQXg6g=="
          />

          <input type="hidden" name="by" value="destroy" />
          <div class="form-group">
            <p>当然不在想使用这个账号的时候，可以选择删除账号。</p>
            <p>删除以后数据将会保留，以匿名的方式存在，你的账号将无法再登陆。</p>
          </div>
          <div class="form-group">
            <input class="form-control" placeholder="要删除账号，请输入你的密码" type="password" name="user[current_password]" id="user_current_password"
            />
          </div>
          <input type="submit" name="commit" value="确定删除我的账号" class="btn btn-danger" data-disable-with="正在提交" />
        </form>
        <div class="heading">绑定其他帐号用于登录</div>
      </div>
    </div>
  </div>
</div>

lib/mipha_web/templates/setting/password.html.eex
<div class="row">
  <div class="col-sm-2 col-md-offset-1 setting-menu">
    <%= render "_sidebar.html", assigns %>
  </div>

  <div class="col-md-10">
    <div class="alert alert-warning">
      <%= gettext "Note! You will need to log in again after updating your password." %>
    </div>

    <div class="card">
      <div class="card-body">
        <%= form_for @changeset, setting_path(@conn, :update), fn f -> %>
          <%= hidden_input f, :by, value: "password" %>

          <div class="form-group">
            <%= label f, :current_password, gettext("Default Password") %>
            <%= password_input f, :current_password, class: "form-control", required: true %>
            <%= error_tag f, :current_password %>
          </div>

          <div class="form-group">
            <%= label f, :password, gettext("New Password") %>
            <%= password_input f, :password, class: "form-control", required: true %>
            <%= error_tag f, :password %>
          </div>

          <div class="form-group">
            <%= label f, :password_confirmation, gettext("Confirmation Password") %>
            <%= password_input f, :password_confirmation, class: "form-control", required: true %>
            <%= error_tag f, :password_confirmation %>
          </div>

          <div class="form-group text-center">
            <%= submit gettext("Update Password"), class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

lib/mipha_web/templates/setting/profile.html.eex
<div class="row">
  <div class="col-sm-2 col-md-offset-1 setting-menu">
    <%= render "_sidebar.html", assigns %>
  </div>

  <div class="col-md-10">
    <div class="card">
      <div class="card-body">
        <%= form_for @changeset, setting_path(@conn, :update), fn f -> %>
          <%= hidden_input f, :by, value: "profile" %>

          <div class="form-group">
            <%= label f, :location_id, gettext("Location") %>
            <%= select f, :location_id, location_option(), class: "form-control", style: "width: 400px" %>
          </div>

          <div class="form-group">
            <label for="user_github">GitHub</label>
            <div class="input-group">
              <span class="input-group-prepend">
                <span class="input-group-text">https://github.com/</span>
              </span>
              <%= text_input f, :github_handle, class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <%= label f, :website, gettext("Website") %>
            <%= text_input f, :website, class: "form-control", placeholder: "http://" %>
          </div>

          <div class="form-group">
            <%= label f, :tagline, gettext("Tagline") %>
            <%= text_input f, :tagline, class: "form-control" %>
          </div>

          <div class="form-actions hide-ios">
            <%= submit gettext("Update"), class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

lib/mipha_web/templates/setting/reward.html.eex
<div class="row">
  <div class="col-sm-2 col-md-offset-1 setting-menu">
    <%= render "_sidebar.html", assigns %>
  </div>

  <div class="col-md-10">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-md-8">
            <%= form_for @changeset, setting_path(@conn, :update), [multipart: true], fn f -> %>
              <%= hidden_input f, :by, value: "reward" %>

              <div class="form-group form-group-reward-field-alipay">
                <%= label f, :alipay, "支付宝" %>
                <%= file_input f, :alipay, class: "form-control" %>
                <p class="form-text">
                  打开支付宝客户端：右上角 “+” -> 我要收款 -> 设定金额 -> 保存二维码图片
                </p>
              </div>

              <div class="form-group form-group-reward-field-wechat">
                <%= label f, :wechat, "微信" %>
                <%= file_input f, :wechat, class: "form-control" %>
                <p class="form-text">
                  打开微信手机客户端：右上角 “+” -> 收付款 -> 我要收款 -> 保存二维码图片
                </p>
              </div>

              <div class="form-actions hide-ios">
                <%= submit "更新资料", class: "btn btn-primary" %>
              </div>
            <% end %>
          </div>
          <div class="col-md-4">
            <div class="markdown">
              <h3>关于打赏</h3>
              <p>打赏功能为了鼓励分享而设计。</p>
              <p>上传你的微信、支付宝
                <strong>收款二维码</strong>，之后打赏按钮将会出现在 “个人主页” 和 “文章末尾” 显示。
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

lib/mipha_web/templates/setting/show.html.eex
<div class="row">
  <div class="col-sm-2 col-md-offset-1 setting-menu">
    <%= render "_sidebar.html", assigns %>
  </div>

  <div class="col-md-10">
    <div class="card">
      <div class="card-body">
        <%= form_for @changeset, setting_path(@conn, :update), [multipart: true], fn f -> %>
          <%= hidden_input f, :by, value: "show" %>
          <div class="row">
            <div class="col-sm-9">
              <div class="form-group">
                <%= text_input f, :email, class: "form-control", disabled: true %>
              </div>

              <div class="form-group">
                <%= checkbox(f, :email_public) %> <%= gettext "Public Email" %>

              </div>

              <div class="form-group">
                <%= file_input f, :avatar %>
                <div class="form-text">
                <%= gettext "Upload avatar" %>
                </div>
              </div>

              <div class="form-group">
                <%= textarea f, :bio, class: "form-control", placeholder: "Add user bio", rows: 4 %>
                <%= error_tag f, :bio %>
              </div>
            </div>
            <div class="col-sm-3">
              <div class="form-group avatar-preview" style="text-align: center;">
                <img class="media-object avatar-96" src="<%= qn_url(@current_user.avatar) %>" />
              </div>
            </div>
          </div>
          <div class="form-actions hide-ios">
            <%= submit gettext("Update"), class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>