lib/mipha_web/router.ex
defmodule MiphaWeb.Router do
  use MiphaWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug Ueberauth
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MiphaWeb.Plug.CurrentUser
    plug MiphaWeb.Plug.Locale
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admin do
    plug :put_layout, {MiphaWeb.LayoutView, :admin}
    plug MiphaWeb.Plug.RequireAdmin
  end

  scope "/auth", MiphaWeb do
    pipe_through(:browser)

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
  end

  scope "/", MiphaWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get "/", TopicController, :index
    get "/search", SearchController, :index
    get "/search/users", SearchController, :users
    get "/markdown", PageController, :markdown
    get("/join", SessionController, :new, as: :join)
    post("/join", SessionController, :create, as: :join)
    get "/excaptcha", SessionController, :excaptcha
    get "/login", AuthController, :login
    get("/logout", AuthController, :delete, as: :logout)

    get "/u/:name", UserController, :show
    get("/u/:name/topics", UserController, :topics, as: :user_topics)
    get("/u/:name/replies", UserController, :replies, as: :user_replies)
    get("/u/:name/stars", UserController, :stars, as: :user_stars)
    get("/u/:name/collections", UserController, :collections, as: :user_collections)
    post("/u/:name/follow", UserController, :follow, as: :user_follow)
    post("/u/:name/unfollow", UserController, :unfollow, as: :user_unfollow)
    get("/u/:name/followers", UserController, :followers, as: :user_followers)
    get("/u/:name/following", UserController, :following, as: :user_following)
    get("/u/:name/reward", UserController, :reward, as: :user_reward)

    get "/users", UserController, :index
    get "/forgot_password", UserController, :forgot_password
    get "/reset_password", UserController, :reset_password
    # get "/verify", UserController, :verify_email
    put "/users/update_password", UserController, :update_password
    post "/users/sent_forgot_password_email", UserController, :sent_forgot_password_email
    post "/users/sent_verify_email", UserController, :sent_verify_email
    resources("/teams", TeamController)
    get "/teams/:id/people", TeamController, :people

    # topic
    get "/jobs", TopicController, :jobs
    get "/topics/no_reply", TopicController, :no_reply
    get "/topics/popular", TopicController, :popular
    get "/topics/featured", TopicController, :featured
    get "/topics/educational", TopicController, :educational

    post "/topics/:id/star", TopicController, :star
    post "/topics/:id/unstar", TopicController, :unstar
    post "/topics/:id/collection", TopicController, :collection
    post "/topics/:id/uncollection", TopicController, :uncollection
    post "/topics/:id/suggest", TopicController, :suggest
    post "/topics/:id/unsuggest", TopicController, :unsuggest
    post "/topics/:id/close", TopicController, :close
    post "/topics/:id/open", TopicController, :open
    post "/topics/:id/excellent", TopicController, :excellent
    post "/topics/:id/normal", TopicController, :normal

    resources "/topics", TopicController do
      resources "/replies", ReplyController do
        post "/star", ReplyController, :star
        post "/unstar", ReplyController, :unstar
      end
    end

    resources("/notifications", NotificationController, only: ~w(index)a)
    post "/notifications/make_read", NotificationController, :make_read
    delete "/notifications/clean", NotificationController, :clean

    resources("/locations", LocationController, only: ~w(index show)a)
    resources("/companies", CompanyController, only: ~w(index show)a)

    # User profile
    resources "/setting", SettingController, only: ~w(show update)a, singleton: true do
      get("/account", SettingController, :account, as: :account)
      get("/password", SettingController, :password, as: :password)
      get("/profile", SettingController, :profile, as: :profile)
      get("/reward", SettingController, :reward, as: :reward)
    end
  end

  scope "/admin", MiphaWeb.Admin, as: :admin do
    pipe_through(~w(browser admin)a)

    get "/", PageController, :index
    resources("/users", UserController, only: ~w(index delete)a)
    resources("/nodes", NodeController)
    resources("/topics", TopicController, only: ~w(index)a)
    resources("/replies", ReplyController, only: ~w(index show delete)a)
    resources("/companies", CompanyController, only: ~w(index delete)a)
    resources("/teams", TeamController, only: ~w(index delete)a)
    resources("/notifications", NotificationController, only: ~w(index show delete)a)
  end

  # Other scopes may use custom stacks.
  scope "/api", MiphaWeb do
    pipe_through(:api)

    post "/topics/preview", TopicController, :preview
    post "/callback/qiniu", CallbackController, :qiniu
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
end

lib/mipha_web/templates/page/_locations.html.eex
<div class="index-locations card">
  <div class="card-header">
    <%= gettext "Hot Cities" %>
  </div>
  <div class="card-body location-list" style="text-align:center;">
    <%= for item <- @locations do %>
      <span class="name">
        <%= link item.name, to: location_path(@conn, :show, item) %>
      </span>
    <% end %>
  </div>
</div>

lib/mipha_web/templates/page/_topic.html.eex
<div class="topic media">
  <div class="avatar">
    <a title="<%= @item.user.username %>" href="/u/<%= @item.user.username %>">
      <img class="media-object avatar-48" src="<%= @item.user.avatar %>">
    </a>
  </div>
  <div class="infos media-body">
    <div class="title media-heading">
      <a title="<%= @item.title %>" href="/topics/<%= @item.id %>">
        <span class="node"><%= @item.node && @item.node.name %></span>
        <%= @item.title %>
      </a>
      <i title="" class="fa fa-diamond" data-toggle="tooltip" data-original-title="精华帖"></i>
    </div>
    <div class="info">
      <a class="user-name" href="/u/<%= @item.user.username %>"><%= @item.user.username %></a>
      <span class="hidden-mobile">
        • 最后由
        <a class="user-name" href="/u/<%= @item.last_reply_user.username %>"><%= @item.last_reply_user && @item.last_reply_user.username %></a> 回复于
        <abbr class="timeago" title="2018年06月23日">6 天前</abbr>
      </span>
    </div>
  </div>
  <div class="count media-right">
    <a class="state-false" href="/topics/<%= @item.id %>#reply-343677"><%= @item.reply_count %></a>
  </div>
</div>

lib/mipha_web/templates/page/index.html.eex
<%#= render "_nodes.html", assigns %>
<%#= render "_locations.html", assigns %>

lib/mipha_web/templates/page/markdown.html.eex
<div class="card markdown">
  <div class="card-body">
    <h1><%= gettext "Markdown Guide" %></h1>
    <div class="row">
      <div class="col-md-6">
        <pre><code><%= @markdown_ex %></code></pre>
      </div>
      <div class="col-md-6">
        <%= markdown(@markdown_ex)%>
      </div>
    </div>
  </div>
</div>

lib/mipha_web/templates/page/search.html.eex
<div class="card">
  <h1>Search Page</h1>
</div>