lib/mipha_web/router.ex
defmodule MiphaWeb.Router do
  use MiphaWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug Ueberauth
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MiphaWeb.Plug.CurrentUser
    plug MiphaWeb.Plug.Locale
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admin do
    plug :put_layout, {MiphaWeb.LayoutView, :admin}
    plug MiphaWeb.Plug.RequireAdmin
  end

  scope "/auth", MiphaWeb do
    pipe_through(:browser)

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
  end

  scope "/", MiphaWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get "/", TopicController, :index
    get "/search", SearchController, :index
    get "/search/users", SearchController, :users
    get "/markdown", PageController, :markdown
    get("/join", SessionController, :new, as: :join)
    post("/join", SessionController, :create, as: :join)
    get "/excaptcha", SessionController, :excaptcha
    get "/login", AuthController, :login
    get("/logout", AuthController, :delete, as: :logout)

    get "/u/:name", UserController, :show
    get("/u/:name/topics", UserController, :topics, as: :user_topics)
    get("/u/:name/replies", UserController, :replies, as: :user_replies)
    get("/u/:name/stars", UserController, :stars, as: :user_stars)
    get("/u/:name/collections", UserController, :collections, as: :user_collections)
    post("/u/:name/follow", UserController, :follow, as: :user_follow)
    post("/u/:name/unfollow", UserController, :unfollow, as: :user_unfollow)
    get("/u/:name/followers", UserController, :followers, as: :user_followers)
    get("/u/:name/following", UserController, :following, as: :user_following)
    get("/u/:name/reward", UserController, :reward, as: :user_reward)

    get "/users", UserController, :index
    get "/forgot_password", UserController, :forgot_password
    get "/reset_password", UserController, :reset_password
    # get "/verify", UserController, :verify_email
    put "/users/update_password", UserController, :update_password
    post "/users/sent_forgot_password_email", UserController, :sent_forgot_password_email
    post "/users/sent_verify_email", UserController, :sent_verify_email
    resources("/teams", TeamController)
    get "/teams/:id/people", TeamController, :people

    # topic
    get "/jobs", TopicController, :jobs
    get "/topics/no_reply", TopicController, :no_reply
    get "/topics/popular", TopicController, :popular
    get "/topics/featured", TopicController, :featured
    get "/topics/educational", TopicController, :educational

    post "/topics/:id/star", TopicController, :star
    post "/topics/:id/unstar", TopicController, :unstar
    post "/topics/:id/collection", TopicController, :collection
    post "/topics/:id/uncollection", TopicController, :uncollection
    post "/topics/:id/suggest", TopicController, :suggest
    post "/topics/:id/unsuggest", TopicController, :unsuggest
    post "/topics/:id/close", TopicController, :close
    post "/topics/:id/open", TopicController, :open
    post "/topics/:id/excellent", TopicController, :excellent
    post "/topics/:id/normal", TopicController, :normal

    resources "/topics", TopicController do
      resources "/replies", ReplyController do
        post "/star", ReplyController, :star
        post "/unstar", ReplyController, :unstar
      end
    end

    resources("/notifications", NotificationController, only: ~w(index)a)
    post "/notifications/make_read", NotificationController, :make_read
    delete "/notifications/clean", NotificationController, :clean

    resources("/locations", LocationController, only: ~w(index show)a)
    resources("/companies", CompanyController, only: ~w(index show)a)

    # User profile
    resources "/setting", SettingController, only: ~w(show update)a, singleton: true do
      get("/account", SettingController, :account, as: :account)
      get("/password", SettingController, :password, as: :password)
      get("/profile", SettingController, :profile, as: :profile)
      get("/reward", SettingController, :reward, as: :reward)
    end
  end

  scope "/admin", MiphaWeb.Admin, as: :admin do
    pipe_through(~w(browser admin)a)

    get "/", PageController, :index
    resources("/users", UserController, only: ~w(index delete)a)
    resources("/nodes", NodeController)
    resources("/topics", TopicController, only: ~w(index)a)
    resources("/replies", ReplyController, only: ~w(index show delete)a)
    resources("/companies", CompanyController, only: ~w(index delete)a)
    resources("/teams", TeamController, only: ~w(index delete)a)
    resources("/notifications", NotificationController, only: ~w(index show delete)a)
  end

  # Other scopes may use custom stacks.
  scope "/api", MiphaWeb do
    pipe_through(:api)

    post "/topics/preview", TopicController, :preview
    post "/callback/qiniu", CallbackController, :qiniu
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
end

lib/mipha_web/controllers/session_controller.ex
defmodule MiphaWeb.SessionController do
  use MiphaWeb, :controller

  alias Mipha.{Accounts, Mailer, Token}
  alias MiphaWeb.Email

  plug :authorized_user

  def new(conn, _params) do
    changeset = Accounts.user_register_changeset()
    render(conn, :new, changeset: changeset)
  end

  def excaptcha(conn, _) do
    {:ok, text, img_binary} = Captcha.get(50_000)

    conn
    |> put_session(:excaptcha, text)
    |> put_resp_header("Cache-Control", "no-cache, no-store, max-age=0, must-revalidate")
    |> put_resp_header("Pragma", "no-cache")
    |> put_resp_content_type("image/gif")
    |> send_resp(200, img_binary)
  end

  def create(conn, %{"user" => user_params, "_excaptcha" => captcha}) do
    # Validation captcha.
    is_true_captcha =
      conn
      |> get_session(:excaptcha)
      |> String.equivalent?(captcha)

    unless is_true_captcha do
      changeset = Accounts.user_register_changeset(user_params)

      conn
      |> put_flash(:danger, gettext("captcha error, pls input again."))
      |> render(:new, changeset: changeset)
    end

    case Accounts.register_user(user_params) do
      {:ok, user} ->
        sent_welcome_email(user)

        conn
        |> ok_login(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:danger, gettext("Register failed. pls try again."))
        |> render(:new, changeset: changeset)
    end
  end

  defp sent_welcome_email(user) do
    user
    |> Token.generate_token()
    |> Email.welcome(user)
    |> Mailer.deliver_later()
  end

  defp ok_login(conn, user) do
    conn
    |> put_flash(:info, gettext("Registered successfully"))
    |> put_session(:current_user, user.id)
    |> redirect(to: "/")
  end

  # if user login,can't reach this controller.
  defp authorized_user(conn, _) do
    if current_user(conn) do
      conn
      |> put_flash(:danger, "You has logged in")
      |> redirect(to: "/")
    else
      conn
    end
  end
end

lib/mipha_web/views/session_view.ex
defmodule MiphaWeb.SessionView do
  use MiphaWeb, :view
end

lib/mipha_web/templates/session/new.html.eex
<div class="row">
  <div class="col"></div>
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header"><%= gettext "Register" %></div>
      <div class="card-body">
        <%= form_for @changeset, join_path(@conn, :create), fn f -> %>
          <%= if @changeset.action do %>
            <div class="alert alert-danger">
              <p>Oops, something went wrong! Please check the errors below.</p>
            </div>
          <% end %>
          <div class="form-group">
            <%= text_input f, :username, class: "form-control", required: true, placeholder: "Username", tabindex: 1 %>
            <%= error_tag f, :username %>
          </div>
          <div class="form-group">
            <%= text_input f, :email, class: "form-control", required: true, placeholder: "Email", tabindex: 2 %>
            <%= error_tag f, :email %>
          </div>
          <div class="form-group">
            <%= password_input f, :password, class: "form-control", required: true, placeholder: "Password", tabindex: 3 %>
          </div>
          <div class="form-group">
            <div class="input-group">
              <input class="form-control input-lg" placeholder="验证码" name="_excaptcha" type="text" autocorrect="off" autocapitalize="off" pattern="[a-zA-Z]*" maxlength="5" autocomplete="off">
              <span class="input-group-addon input-group-captcha"><a class="excaptcha-image-box" href="#"><img class="excaptcha-image" src="<%= session_path(@conn, :excaptcha) %>"></a></span>
            </div>
          </div>
          <div class="form-group text-center">
            <%= submit class: "btn btn-primary btn-block btn-lg", tabindex: 4 do %>
              <i class="fa fa-sign-in" aria-hidden="true"></i>
              <span><%= gettext "Register" %></span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col"></div>
</div>