lib/mipha_web/router.ex
defmodule MiphaWeb.Router do
  use MiphaWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug Ueberauth
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MiphaWeb.Plug.CurrentUser
    plug MiphaWeb.Plug.Locale
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admin do
    plug :put_layout, {MiphaWeb.LayoutView, :admin}
    plug MiphaWeb.Plug.RequireAdmin
  end

  scope "/auth", MiphaWeb do
    pipe_through(:browser)

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
  end

  scope "/", MiphaWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get "/", TopicController, :index
    get "/search", SearchController, :index
    get "/search/users", SearchController, :users
    get "/markdown", PageController, :markdown
    get("/join", SessionController, :new, as: :join)
    post("/join", SessionController, :create, as: :join)
    get "/excaptcha", SessionController, :excaptcha
    get "/login", AuthController, :login
    get("/logout", AuthController, :delete, as: :logout)

    get "/u/:name", UserController, :show
    get("/u/:name/topics", UserController, :topics, as: :user_topics)
    get("/u/:name/replies", UserController, :replies, as: :user_replies)
    get("/u/:name/stars", UserController, :stars, as: :user_stars)
    get("/u/:name/collections", UserController, :collections, as: :user_collections)
    post("/u/:name/follow", UserController, :follow, as: :user_follow)
    post("/u/:name/unfollow", UserController, :unfollow, as: :user_unfollow)
    get("/u/:name/followers", UserController, :followers, as: :user_followers)
    get("/u/:name/following", UserController, :following, as: :user_following)
    get("/u/:name/reward", UserController, :reward, as: :user_reward)

    get "/users", UserController, :index
    get "/forgot_password", UserController, :forgot_password
    get "/reset_password", UserController, :reset_password
    # get "/verify", UserController, :verify_email
    put "/users/update_password", UserController, :update_password
    post "/users/sent_forgot_password_email", UserController, :sent_forgot_password_email
    post "/users/sent_verify_email", UserController, :sent_verify_email
    resources("/teams", TeamController)
    get "/teams/:id/people", TeamController, :people

    # topic
    get "/jobs", TopicController, :jobs
    get "/topics/no_reply", TopicController, :no_reply
    get "/topics/popular", TopicController, :popular
    get "/topics/featured", TopicController, :featured
    get "/topics/educational", TopicController, :educational

    post "/topics/:id/star", TopicController, :star
    post "/topics/:id/unstar", TopicController, :unstar
    post "/topics/:id/collection", TopicController, :collection
    post "/topics/:id/uncollection", TopicController, :uncollection
    post "/topics/:id/suggest", TopicController, :suggest
    post "/topics/:id/unsuggest", TopicController, :unsuggest
    post "/topics/:id/close", TopicController, :close
    post "/topics/:id/open", TopicController, :open
    post "/topics/:id/excellent", TopicController, :excellent
    post "/topics/:id/normal", TopicController, :normal

    resources "/topics", TopicController do
      resources "/replies", ReplyController do
        post "/star", ReplyController, :star
        post "/unstar", ReplyController, :unstar
      end
    end

    resources("/notifications", NotificationController, only: ~w(index)a)
    post "/notifications/make_read", NotificationController, :make_read
    delete "/notifications/clean", NotificationController, :clean

    resources("/locations", LocationController, only: ~w(index show)a)
    resources("/companies", CompanyController, only: ~w(index show)a)

    # User profile
    resources "/setting", SettingController, only: ~w(show update)a, singleton: true do
      get("/account", SettingController, :account, as: :account)
      get("/password", SettingController, :password, as: :password)
      get("/profile", SettingController, :profile, as: :profile)
      get("/reward", SettingController, :reward, as: :reward)
    end
  end

  scope "/admin", MiphaWeb.Admin, as: :admin do
    pipe_through(~w(browser admin)a)

    get "/", PageController, :index
    resources("/users", UserController, only: ~w(index delete)a)
    resources("/nodes", NodeController)
    resources("/topics", TopicController, only: ~w(index)a)
    resources("/replies", ReplyController, only: ~w(index show delete)a)
    resources("/companies", CompanyController, only: ~w(index delete)a)
    resources("/teams", TeamController, only: ~w(index delete)a)
    resources("/notifications", NotificationController, only: ~w(index show delete)a)
  end

  # Other scopes may use custom stacks.
  scope "/api", MiphaWeb do
    pipe_through(:api)

    post "/topics/preview", TopicController, :preview
    post "/callback/qiniu", CallbackController, :qiniu
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
end

lib/mipha/topics/node.ex
defmodule Mipha.Topics.Node do
  @moduledoc false
  use Ecto.Schema
  import Ecto.{Changeset, Query}

  alias Mipha.Repo
  alias Mipha.Topics.{Topic, Node}

  @type t :: %Node{}

  schema "nodes" do
    field :name, :string
    field :position, :integer
    field :summary, :string

    belongs_to :parent, Node, foreign_key: :parent_id

    has_many :topics, Topic
    has_many :children, Node, foreign_key: :parent_id

    timestamps()
  end

  @doc """
  Returns the children node.
  """
  @spec is_child(Ecto.Queryable.t()) :: Ecto.Query.t()
  def is_child(query \\ __MODULE__), do: from(q in query, where: not is_nil(q.parent_id))

  @doc """
  Returns the parent of node.
  """
  @spec is_parent(Ecto.Queryable.t()) :: Ecto.Query.t()
  def is_parent(query \\ __MODULE__), do: from(q in query, where: is_nil(q.parent_id))

  @doc """
  Preloads the children of a node.
  """
  @spec preload_children(t()) :: t()
  def preload_children(node), do: Repo.preload(node, :children)

  @doc false
  def changeset(node, attrs) do
    permitted_attrs = ~w(
      name
      summary
      position
      parent_id
    )a

    required_attrs = ~w(
      name
    )a

    node
    |> cast(attrs, permitted_attrs)
    |> validate_required(required_attrs)
  end
end

lib/mipha/topics/queries.ex
defmodule Mipha.Topics.Queries do
  @moduledoc false

  import Ecto.Query
  alias Mipha.Topics.{Topic, Node}

  @doc """
  Returns the list topics.
  """
  @spec list_topics :: Ecto.Query.t()
  def list_topics, do: Topic

  @doc """
  Returns the list nodes.
  """
  @spec list_nodes :: Ecto.Query.t()
  def list_nodes, do: Node

  @doc """
  Returns the the type equal job topics.
  """
  @spec job_topics :: Ecto.Query.t()
  def job_topics do
    Topic.job()
    |> preload([:user, :node, :last_reply_user])
  end

  @doc """
  Filter the list of topics.

  ## Examples

      iex> cond_topics()
      Ecto.Query.t()

      iex> cond_topics(type: :educational)
      Ecto.Query.t()

      iex> cond_topics(node: %Node{})
      Ecto.Query.t()

      iex> cond_topics(user: %User{})
      Ecto.Query.t()

  """
  @spec cond_topics(Keyword.t()) :: Ecto.Query.t()
  def cond_topics(opts) do
    opts
    |> filter_from_clauses
    |> Topic.base_order()
    |> preload([:user, :node, :last_reply_user])
  end

  defp filter_from_clauses(opts), do: do_filter_from_clauses(opts)

  defp do_filter_from_clauses(type: :educational), do: Topic.educational()
  defp do_filter_from_clauses(type: :featured), do: Topic.featured()
  defp do_filter_from_clauses(type: :no_reply), do: Topic.no_reply()
  defp do_filter_from_clauses(type: :popular), do: Topic.popular()
  defp do_filter_from_clauses(node: node), do: Topic.by_node(node)
  defp do_filter_from_clauses(user: user), do: Topic.by_user(user)
  defp do_filter_from_clauses(user_ids: user_ids), do: Topic.by_user_ids(user_ids)
  defp do_filter_from_clauses(_), do: Topic
end

lib/mipha_web/controllers/admin/topic_controller.ex
defmodule MiphaWeb.Admin.TopicController do
  use MiphaWeb, :controller

  alias Mipha.Topics.Queries

  def index(conn, params) do
    result = Queries.list_topics() |> Turbo.Ecto.turbo(params)
    render(conn, :index, topics: result.datas, paginate: result.paginate)
  end
end

lib/mipha_web/controllers/topic_controller.ex
defmodule MiphaWeb.TopicController do
  use MiphaWeb, :controller

  alias Mipha.{Topics, Stars, Collections, Markdown}
  alias Mipha.Topics.Queries

  plug MiphaWeb.Plug.RequireUser when action in ~w(
    new create edit update
    star unstar collection uncollection
    unsuggest suggest close open excellent normal
  )a

  @intercepted_action ~w(index no_reply popular featured educational)a

  def action(conn, _) do
    conn
    |> action_name
    |> do_fragment(conn)
  end

  defp do_fragment(action_name, conn) when action_name in @intercepted_action do
    opts =
      if conn.params["node_id"] do
        [node: Topics.get_node!(conn.params["node_id"])]
      else
        [type: action_name(conn)]
      end

    parent_nodes = Topics.list_parent_nodes()

    result =
      opts
      |> Queries.cond_topics()
      |> Turbo.Ecto.turbo(conn.params)

    render(conn, action_name(conn),
      asset: "topics",
      topics: result.datas,
      paginate: result.paginate,
      parent_nodes: parent_nodes
    )
  end

  defp do_fragment(:suggest, conn) do
    topic = Topics.get_topic!(conn.params["id"])
    attrs = %{"suggested_at" => Timex.now()}
    flash = gettext("Pin")

    do_update(conn, topic, attrs, flash)
  end

  defp do_fragment(:unsuggest, conn) do
    topic = Topics.get_topic!(conn.params["id"])
    attrs = %{"suggested_at" => nil}
    flash = gettext("Unpin")

    do_update(conn, topic, attrs, flash)
  end

  defp do_fragment(:close, conn) do
    topic = Topics.get_topic!(conn.params["id"])
    attrs = %{"closed_at" => Timex.now()}
    flash = gettext("Closed")

    do_update(conn, topic, attrs, flash)
  end

  defp do_fragment(:open, conn) do
    topic = Topics.get_topic!(conn.params["id"])
    attrs = %{"closed_at" => nil}
    flash = gettext("Opened")

    do_update(conn, topic, attrs, flash)
  end

  defp do_fragment(:excellent, conn) do
    topic = Topics.get_topic!(conn.params["id"])
    attrs = %{"type" => "featured"}
    flash = gettext("Featured topic")

    do_update(conn, topic, attrs, flash)
  end

  defp do_fragment(:normal, conn) do
    topic = Topics.get_topic!(conn.params["id"])
    attrs = %{"type" => "normal"}
    flash = gettext("Normal topic")

    do_update(conn, topic, attrs, flash)
  end

  defp do_fragment(_, conn) do
    apply(__MODULE__, action_name(conn), [conn, conn.params])
  end

  # update topic
  defp do_update(conn, topic, attrs, flash) do
    {:ok, topic} = Topics.update_topic(topic, attrs)

    conn
    |> put_flash(:success, flash)
    |> redirect(to: topic_path(conn, :show, topic))
  end

  def jobs(conn, params) do
    parent_nodes = Topics.list_parent_nodes()
    result = Turbo.Ecto.turbo(Queries.job_topics(), params)

    render(conn, :jobs,
      parent_nodes: parent_nodes,
      topics: result.datas,
      paginate: result.paginate
    )
  end

  def new(conn, _params) do
    changeset = Topics.change_topic()
    parent_nodes = Topics.list_parent_nodes()

    render(conn, :new,
      changeset: changeset,
      parent_nodes: parent_nodes
    )
  end

  def edit(conn, %{"id" => id}) do
    topic = Topics.get_topic!(id)
    changeset = Topics.change_topic(topic)
    parent_nodes = Topics.list_parent_nodes()

    render(conn, :edit,
      topic: topic,
      changeset: changeset,
      parent_nodes: parent_nodes
    )
  end

  def create(conn, %{"topic" => topic_params}) do
    case Topics.insert_topic(current_user(conn), topic_params) do
      {:ok, %{topic: topic}} ->
        conn
        |> put_flash(:success, gettext("Topic created successfully."))
        |> redirect(to: topic_path(conn, :show, topic))

      {:error, :topic, %Ecto.Changeset{} = changeset, _} ->
        parent_nodes = Topics.list_parent_nodes()

        conn
        |> put_flash(:danger, gettext("Create topic failed, pls select node_id."))
        |> render(:new, changeset: changeset, parent_nodes: parent_nodes)
    end
  end

  def update(conn, %{"id" => id, "topic" => topic_params}) do
    topic = Topics.get_topic!(id)

    case Topics.update_topic(topic, topic_params) do
      {:ok, topic} ->
        conn
        |> put_flash(:success, gettext("Topic updated successfully."))
        |> redirect(to: topic_path(conn, :show, topic))

      {:error, %Ecto.Changeset{} = changeset} ->
        parent_nodes = Topics.list_parent_nodes()
        render(conn, :edit, topic: topic, changeset: changeset, parent_nodes: parent_nodes)
    end
  end

  def show(conn, %{"id" => id}) do
    topic = Topics.get_topic!(id)

    # Same session, same visit counter.
    if is_nil(get_session(conn, "visited_topic_#{topic.id}")) do
      # increment topic visit count.
      Topics.topic_visit_counter(topic)

      conn
      |> put_session("visited_topic_#{topic.id}", topic.id)
      |> render(:show, topic: topic)
    else
      render(conn, :show, topic: topic)
    end
  end

  def delete(conn, %{"id" => id}) do
    topic = Topics.get_topic!(id)
    {:ok, _topic} = Topics.delete_topic(topic)

    conn
    |> put_flash(:info, gettext("Topic deleted successfully."))
    |> redirect(to: topic_path(conn, :index))
  end

  def preview(conn, %{"body" => body}) do
    json(conn, %{body: Markdown.render(body)})
  end

  def star(conn, %{"id" => id}) do
    topic = Topics.get_topic!(id)

    attrs = %{
      user_id: current_user(conn).id,
      topic_id: topic.id
    }

    case Stars.insert_star(attrs) do
      {:ok, _} ->
        conn
        |> put_flash(:info, gettext("Star successfully"))
        |> redirect(to: topic_path(conn, :show, topic))

      {:error, _} ->
        conn
        |> put_flash(:danger, gettext("Star failed"))
        |> redirect(to: topic_path(conn, :show, topic))
    end
  end

  def unstar(conn, %{"id" => id}) do
    topic = Topics.get_topic!(id)

    attrs = [
      user_id: current_user(conn).id,
      topic_id: topic.id
    ]

    case Stars.delete_star(attrs) do
      {:ok, _} ->
        conn
        |> put_flash(:info, gettext("Unstar successfully"))
        |> redirect(to: topic_path(conn, :show, topic))

      {:error, _} ->
        conn
        |> put_flash(:danger, gettext("Unstar failed"))
        |> redirect(to: topic_path(conn, :show, topic))
    end
  end

  def collection(conn, %{"id" => id}) do
    topic = Topics.get_topic!(id)

    attrs = %{
      user_id: current_user(conn).id,
      topic_id: topic.id
    }

    case Collections.insert_collection(attrs) do
      {:ok, _} ->
        conn
        |> put_flash(:info, gettext("Collection successfully"))
        |> redirect(to: topic_path(conn, :show, topic))

      {:error, _} ->
        conn
        |> put_flash(:danger, gettext("Collection failed"))
        |> redirect(to: topic_path(conn, :show, topic))
    end
  end

  def uncollection(conn, %{"id" => id}) do
    topic = Topics.get_topic!(id)

    attrs = [
      user_id: current_user(conn).id,
      topic_id: topic.id
    ]

    case Collections.delete_collection(attrs) do
      {:ok, _} ->
        conn
        |> put_flash(:info, gettext("Uncollection successfully"))
        |> redirect(to: topic_path(conn, :show, topic))

      {:error, _} ->
        conn
        |> put_flash(:danger, gettext("Uncollection failed"))
        |> redirect(to: topic_path(conn, :show, topic))
    end
  end
end

lib/mipha_web/views/admin/topic_view.ex
defmodule MiphaWeb.Admin.TopicView do
  use MiphaWeb, :view
end

lib/mipha_web/views/topic_view.ex
defmodule MiphaWeb.TopicView do
  use MiphaWeb, :view

  alias Mipha.{
    Stars,
    Collections,
    Topics,
    Accounts,
    Replies
  }

  @doc """
  判断是否已 Star
  """
  def has_starred?(clauses) do
    if is_nil(Keyword.get(clauses, :user)), do: false, else: Stars.has_starred?(clauses)
  end

  @doc """
  判断是否已收藏该帖。
  """
  def has_collected?(current_user, topic) do
    if is_nil(current_user),
      do: false,
      else: Collections.has_collected?(user: current_user, topic: topic)
  end

  @doc """
  获取全站 topic 个数
  """
  def get_topic_count do
    Topics.get_total_topic_count()
  end

  @doc """
  获取全站 topic 个数
  """
  def get_reply_count do
    Replies.get_total_reply_count()
  end

  @doc """
  获取全站 user 个数
  """
  def get_user_count do
    Accounts.get_total_user_count()
  end

  @doc """
  是否是受欢迎的帖子评论。
  """
  def popular(reply) do
    if reply.star_count >= 5, do: "popular"
  end
end

lib/mipha_web/templates/topic/_form.html.eex
<div class="card-body">
  <%= render "_node_selector.html", assigns %>
  <%= form_for @changeset, @action, fn f -> %>
    <input name="utf8" type="hidden" value="&#x2713;" />
    <%= hidden_input f, :node_id %>
    <%= error_tag f, :node_id %>
    <div class="form-group">
      <div class="input-group">
        <div class="input-group-prepend">
          <button type="button" class="btn btn-default" id="node-selector-button" data-toggle="modal" data-target="#node-selector">
            <%= Map.get(assigns, :topic) && @topic.node.name || "选择节点..." %>
          </button>
        </div>
        <%= text_input f, :title, class: "form-control", required: true, placeholder: "Title" %>
        <%= error_tag f, :title %>
      </div>
    </div>
    <%= render "_editor_toolbar.html", assigns %>

    <div class="form-group">
      <%= textarea f, :body, class: "form-control topic-editor closewarning", required: true, placeholder: "Body", rows: 20 %>
      <%= error_tag f, :body %>
    </div>
    <div class="form-actions hide-ios">
      <%= submit gettext("Submit"), class: "btn btn-primary" %>
      <div class="pull-right hide-ios">
        <a href="/markdown" target="_blank"><i class="fa fa-tip"></i>
          <%= gettext "Markdown Guide" %>
        </a>
      </div>
    </div>
  <% end %>
</div>

lib/mipha_web/templates/topic/_handle_reply.html.eex
<%= if @current_user do %>
  <%= if is_nil(@topic.closed_at) do %>
    <div id="reply" class="card">
      <div class="card-header hide-ios">
        <%= gettext "Reply" %>
      </div>
      <div class="card-body">
        <form id="new_reply" action="/topics/<%= @topic.id %>/replies" accept-charset="UTF-8" method="post">
          <%= render "_editor_toolbar.html", assigns %>
          <input type="hidden" name="_method" value="post" />
          <input type="hidden" name="_csrf_token" value="<%= get_csrf_token() %>" />
          <input type="hidden" name="reply[parent_id]" id="reply_parent_id" />
          <input type="hidden" name="reply[topic_id]" id="reply_topic_id" value="<%= @topic.id %>" />
          <div class="form-group">
            <textarea class="topic-editor form-control" rows="4" tabindex="1" name="reply[content]" id="reply_content"></textarea>
          </div>
          <div class="submit-buttons">
            <button type="submit" id="reply-button" class="btn btn-primary">
              <%= gettext "Submit" %>
            </button>
            <span class="help-inline" style="padding-left: 5px;" title="或者 Ctrl + Enter">
              <kbd>Command</kbd> +
              <kbd>Enter</kbd>
            </span>
            <div class="pull-right">
              <a href="/markdown" target="_blank">
                <%= gettext "Markdown Guide" %>
              </a>
            </div>
          </div>
        </form>
      </div>
    </div>
  <% end %>
<% else %>
  <%= render "_need_register_or_login.html", assigns %>
<% end %>

lib/mipha_web/templates/topic/_need_register_or_login.html.eex
<div class="card">
  <div class="card-body">
    <div id="reply" class="form box">
      <div style="padding:20px;" data-turbolinks-action="replace">
        You need <a class="btn btn-primary btn-sm" href="/login">Login</a>
        to reply, Or
        <a class="btn btn-danger btn-sm" href="/join">Register</a>。
      </div>
    </div>
  </div>
</div>

lib/mipha_web/templates/topic/_node_selector.html.eex
<div class="modal" id="node-selector" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="modal-title"><%= gettext "Nodes" %></div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="index-sections card">
          <div class="card-header"><%= gettext "Nodes" %></div>
          <div class="card-body">
            <div class="row node-list">
              <%= for parent_node <- @parent_nodes do %>
                <div class="node media">
                  <label class="mr-2 media-left"><%= parent_node.name %></label>
                  <span class="nodes media-body">
                    <%= for item <- parent_node.children do %>
                      <span class="name">
                        <a data-id="<%= item.id %>" href="/topics/?node_id=<%= item.id %>"><%= item.name %></a>
                      </span>
                    <% end %>
                  </span>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

lib/mipha_web/templates/topic/_operate_toolbar.html.eex
<div class="opts">
  <%= if has_starred?(user: @current_user, topic: @topic) do %>
    <%= link to: topic_path(@conn, :unstar, @topic), method: :post, class: "likeable active" do %>
      <i class="fa fa-heart"></i>
      <span><%= gettext "%{star_count} stars", star_count: @topic.star_count %></span>
    <% end %>
  <% else %>
    <%= link to: topic_path(@conn, :star, @topic), method: :post, class: "likeable deactive" do %>
      <i class="fa fa-heart"></i>
      <span><%= gettext "%{star_count} stars", star_count: @topic.star_count %></span>
    <% end %>
  <% end %>

  <%= if has_collected?(@current_user, @topic) do %>
    <%= link to: topic_path(@conn, :uncollection, @topic), method: :post, class: "bookmark active" do %>
      <i class="fa fa-bookmark"></i> <%= gettext "Uncollection" %>
    <% end %>
  <% else %>
    <%= link to: topic_path(@conn, :collection, @topic), method: :post, class: "bookmark" do %>
      <i class="fa fa-bookmark"></i> <%= gettext "Collection" %>
    <% end %>
  <% end %>

  <%# 只有管理员可以设置「置顶」或「加精」 %>
  <%= if @current_user && @current_user.is_admin do %>
    <%= if @topic.suggested_at do %>
      <%= link to: topic_path(@conn, :unsuggest, @topic), method: :post do %>
        <i class="fa fa-angle-double-down"></i> <%= gettext "Unpin" %>
      <% end %>
    <% else %>
      <%= link to: topic_path(@conn, :suggest, @topic), method: :post do %>
        <i class="fa fa-angle-double-up"></i> <%= gettext "Pin" %>
      <% end %>
    <% end %>

    <%= if @topic.type == :featured do %>
      <%= link to: topic_path(@conn, :normal, @topic), method: :post, title: "Unmark featured" do %>
        <i class="fa fa-diamond"></i> <%= gettext "Unmark featured" %>
      <% end %>
    <% else %>
      <%= link to: topic_path(@conn, :excellent, @topic), method: :post, title: "Mark featured" do %>
        <i class="fa fa-diamond"></i> <%= gettext "Mark featured" %>
      <% end %>
    <% end %>
  <% end %>

  <%# FIXME 后续考虑权限控制 %>
  <%= if @current_user && @current_user.id == @topic.user_id do %>
    <span class="pull-right opts">
      <%= if @topic.closed_at do %>
        <%= link "", to: topic_path(@conn, :open, @topic), method: :post, title: "Reopen", class: "fa fa-undo" %>
      <% else %>
        <%= link "", to: topic_path(@conn, :close, @topic), method: :post, title: "Closed", class: "fa fa-check" %>
      <% end %>
      <%= link "", to: topic_path(@conn, :edit, @topic), title: "Change Topic", class: "fa fa-pencil" %>
      <%= link "", to: topic_path(@conn, :delete, @topic), title: "Delete Topic", class: "fa fa-trash", method: :delete, data: [confirm: "Are you sure?"] %>
    </span>
  <% end %>
</div>

lib/mipha_web/templates/topic/_replies.html.eex
<div id="replies" class="card">
  <div class="total card-header hide-ios">
    <%= gettext "Total" %>
    <b><%= @topic.reply_count %></b> <%= gettext "replies" %>
  </div>
  <div class="items card-body">
    <%= for {item, idx} <- Enum.with_index(@topic.replies) do %>
      <div class="reply <%= popular(item) %>" data-id="<%= item.id %>" id="reply<%= item.id %>">
        <div id="reply-<%= item.id %>" data-floor="<%= idx + 1 %>">
          <div class="avatar">
            <%= link to: user_path(@conn, :show, item.user.username), title: item.user.username do %>
              <img class="media-object avatar-48" src="<%= qn_url(item.user.avatar) %>" />
            <% end %>
          </div>
          <div class="infos">
            <div class="info">
              <span class="name">
                <%= link item.user.username, to: user_path(@conn, :show, item.user.username), class: "user-name" %>
              </span>
              <span class="sub-info">
                <span class='floor'>#<%= idx + 1 %></span> ·
                <%= time_tag(item.updated_at) %>
              </span>
              <span class="opts pull-right">
                <span class="hideable">
                  <%= link "", to: topic_reply_path(@conn, :edit, @topic, item), title: gettext("Edit reply"), class: "fa fa-pencil" %>
                  <a data-id="<%= item.id %>" data-login="<%= item.user.username %>" title="" class="btn-reply fa fa-mail-reply" href="#"></a>
                </span>
                <%= if has_starred?(user: @current_user, reply: item) do %>
                  <%= link to: topic_reply_reply_path(@conn, :unstar, @topic, item), method: :post, title: "", class: "likeable active" do %>
                    <i class="fa fa-heart"></i>
                    <span><%= item.star_count %> 个赞</span>
                  <% end %>
                <% else %>
                  <%= link to: topic_reply_reply_path(@conn, :star, @topic, item), method: :post, title: "", class: "likeable deactive" do %>
                    <i class="fa fa-heart"></i>
                    <span><%= gettext "%{star_count} stars", star_count: item.star_count %></span>
                  <% end %>
                <% end %>
              </span>
            </div>
            <%= if item.parent_id do %>
              <div class="reply-to-block">
                <div class="info">
                  <%= gettext "Replied to" %>
                  <a>
                    <img class="media-object avatar-16" src="<%= qn_url(item.parent.user.avatar) %>">
                    <span class="user-name"><%= item.parent.user.username %></span>
                  </a>
                </div>
              </div>
            <% end %>
            <div class="markdown">
              <%= markdown(item.content) %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>